# 配置端口号
server:
  port: 8888

#jwt配置
config:
  jwt:
    secret: duxiaozui
    #30分钟过期
    expiration: 1800000
  

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wy_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  #  整合 Redis
  redis:
    host: 192.168.129.130
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: 100ms
  #  整合  MongoDB
  data:
    mongodb:
      host: 127.0.0.1
      database: wy_db
      port: 27017

  servlet:
    #    控制视频上传大小
    multipart:
      enabled: true
      max-file-size: 1GB
      max-request-size: 3GB


  #  配置文件解决兼容问题
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher

#  MybatisPlus相关配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      update-strategy: not_empty
      insert-strategy: not_empty
      logic-not-delete-value: 1
      logic-delete-value: 0
  mapper-locations: classpath:/com/dxz/web/*/mapper/xml/*.xml

